export const posts = [
  {
    heading: "Dummy post sample heading 1",
    id: "1",
    creator: "Adam",
    avatar: "https://github.com/shadcn.png",
    body: "",
    createdAt: "2024-05-26T20:32:52.973Z",
    category:"Technology",
    cardThumbnail:"test.jpeg",
    isDummy: true,
  },
  {
    heading: "Dummy post sample heading 2",
    id: "2",
    creator: "Leon",
    avatar: "https://avatars.githubusercontent.com/u/41151614?v=4",
    body: "",
    createdAt: "2024-05-26T20:32:52.973Z",
    category:"Technology",
    cardThumbnail:"test-1.jpg",
    isDummy: true,
  },
  {
    heading: "Dummy post sample heading 3",
    id: "3",
    creator: "Max",
    avatar: "https://avatars.githubusercontent.com/u/88678143?v=4",
    body: "",
    createdAt: "2024-05-26T20:32:52.973Z",
    category:"Technology",
    cardThumbnail:"test-2.jpg",
    isDummy: true,
  },
  {
    heading: "Dummy post sample heading 4",
    id: "4",
    creator: "Doug",
    avatar: "https://avatars.githubusercontent.com/u/28755051?v=4",
    body: "",
    createdAt: "2024-05-26T20:32:52.973Z",
    category:"Technology",
    cardThumbnail:"test-3.jpg",
    isDummy: true,
  },
  {
    heading: "Dummy post sample heading 5",
    id: "5",
    creator: "Rob",
    avatar: "https://avatars.githubusercontent.com/u/131390720?v=4",
    body: "",
    createdAt: "2024-05-26T21:55:28.500Z",
    category:"Technology",
    cardThumbnail:"test-4.jpg",
    isDummy: true,
  },
]




